artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1JpFsIVXR6RfmIVLafsIwQia8G8B689Zu/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_preprocessing:
  root_dir: artifacts/data_preprocessing
  data_source: artifacts/data_ingestion/CASIA2
  resaved_path: artifacts/data_preprocessing/resaved
  pickle_save: artifacts/data_preprocessing/pickle

trainer_evaluation:
  root_dir: artifacts/model_trainer
  load_data: artifacts/data_preprocessing/pickle
  save_model: artifacts/model_trainer/model

model_evaluation:
  model_path: artifacts/model_trainer/model
  model: model.keras
  load_data: artifacts/data_preprocessing/pickle
  mlflow_uri: https://dagshub.com/sharonjolly/image_forgery_detection_model.mlflow